name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node Environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install Dependencies
      run: |
        npm update
        npm install
    - name: Build
      run: |
        npm build
    - name: Run Tests
      run: |
        npm test
